services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pwl_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  api:
    build: .
    environment:
      - DB_HOST=db
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_started

volumes:
  postgres_data:
