services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pwl_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pwl_db" ]
      interval: 5s
      timeout: 5s
      retries: 3

  api:
    build: .
    environment:
      - DB_HOST=db
      - SECRET_KEY=d7f35f2be70d7a985a39c6e6d118503dc783ecd88673b8d49896473c64047c55
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
