"""add is_admin field into User

Revision ID: 03e7b84a8a89
Revises: ba5aee50a8a5
Create Date: 2025-09-12 12:32:30.436381

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03e7b84a8a89"
down_revision: Union[str, Sequence[str], None] = "ba5aee50a8a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=True))

    # Update all existing rows so there are no NULL values
    op.execute('UPDATE "user" SET is_admin = false')

    # Make the column NOT NULL
    op.alter_column("user", "is_admin", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_admin")
    # ### end Alembic commands ###
