"""add delete CASCADE constraint on shopping_list_id in ShoppingListItem

Revision ID: ba5aee50a8a5
Revises: 06d1868b0774
Create Date: 2025-09-11 09:35:19.846273

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba5aee50a8a5"
down_revision: Union[str, Sequence[str], None] = "06d1868b0774"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_shoppinglistitem_shopping_list_id_shoppinglist"),
        "shoppinglistitem",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_shoppinglistitem_shopping_list_id_shoppinglist"),
        "shoppinglistitem",
        "shoppinglist",
        ["shopping_list_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_shoppinglistitem_shopping_list_id_shoppinglist"),
        "shoppinglistitem",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_shoppinglistitem_shopping_list_id_shoppinglist"),
        "shoppinglistitem",
        "shoppinglist",
        ["shopping_list_id"],
        ["id"],
    )
    # ### end Alembic commands ###
