"""move family members to separate table

Revision ID: c34672a5c973
Revises: 025fa6dcb66c
Create Date: 2025-09-01 11:22:57.049894

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c34672a5c973"
down_revision: Union[str, Sequence[str], None] = "025fa6dcb66c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "familymember",
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("ADMIN", "MEMBER", name="familyrole"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("family_id", "user_id"),
    )
    op.drop_constraint(op.f("family_user_id_fkey"), "family", type_="foreignkey")
    op.drop_column("family", "user_id")
    op.drop_column("family", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "family",
        sa.Column(
            "role",
            postgresql.ENUM("ADMIN", "MEMBER", name="familyrole"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "family", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("family_user_id_fkey"), "family", "user", ["user_id"], ["id"]
    )
    op.drop_table("familymember")
    # ### end Alembic commands ###
